// ── 化粧品成分データベース ────────────────────────────────────
// Phase 4.1: 日本語名・INCI名・表記ゆれ辞書（最低100件）
// データソース参考: 日本化粧品工業連合会(JCIA)・厚生労働省・ISO 16128

const INGREDIENTS_DB = [
  // ── 基本溶媒・保湿剤 ──
  { ja: '水', inci: 'Water', variants: ['精製水', 'イオン交換水', 'Aqua', 'Pure Water', '蒸留水', '滅菌精製水'] },
  { ja: 'グリセリン', inci: 'Glycerin', variants: ['グリセロール', 'Glycerol', '濃グリセリン', '精製グリセリン'] },
  { ja: 'ブチレングリコール', inci: 'Butylene Glycol', variants: ['1,3-ブチレングリコール', '1,3-BG', 'BG', '1,3-ブタンジオール'] },
  { ja: 'プロパンジオール', inci: 'Propanediol', variants: ['1,3-プロパンジオール', 'プロピレングリコール代替'] },
  { ja: 'プロピレングリコール', inci: 'Propylene Glycol', variants: ['1,2-プロパンジオール', 'PG'] },
  { ja: 'ペンチレングリコール', inci: 'Pentylene Glycol', variants: ['1,2-ペンタンジオール'] },
  { ja: 'ヘキシレングリコール', inci: 'Hexylene Glycol', variants: [] },
  { ja: 'ジプロピレングリコール', inci: 'Dipropylene Glycol', variants: ['DPG'] },
  { ja: 'エタノール', inci: 'Alcohol', variants: ['アルコール', 'エチルアルコール', '95%エタノール', '変性アルコール', 'Ethyl Alcohol', 'Denatured Alcohol'] },
  { ja: 'イソプロパノール', inci: 'Isopropanol', variants: ['イソプロピルアルコール', '2-プロパノール'] },

  // ── 油性成分・エモリエント ──
  { ja: 'スクワラン', inci: 'Squalane', variants: ['植物性スクワラン', 'スクアラン'] },
  { ja: 'ホホバ種子油', inci: 'Simmondsia Chinensis (Jojoba) Seed Oil', variants: ['ホホバオイル', 'ジョジョバ油'] },
  { ja: 'シア脂', inci: 'Butyrospermum Parkii (Shea) Butter', variants: ['シアバター', 'カリテバター', 'Shea Butter'] },
  { ja: 'アルガニアスピノサ核油', inci: 'Argania Spinosa Kernel Oil', variants: ['アルガンオイル', 'アルガン油'] },
  { ja: 'ローズヒップ果実油', inci: 'Rosa Canina Fruit Oil', variants: ['ローズヒップオイル'] },
  { ja: 'オリーブ果実油', inci: 'Olea Europaea (Olive) Fruit Oil', variants: ['オリーブオイル', 'オリーブ油'] },
  { ja: 'ヒマワリ種子油', inci: 'Helianthus Annuus (Sunflower) Seed Oil', variants: ['ひまわり油', 'サンフラワーオイル'] },
  { ja: 'パーム油', inci: 'Elaeis Guineensis (Palm) Oil', variants: ['パームオイル'] },
  { ja: 'ヤシ油', inci: 'Cocos Nucifera (Coconut) Oil', variants: ['ココナッツオイル', 'コプラ油'] },
  { ja: 'ミネラルオイル', inci: 'Mineral Oil', variants: ['流動パラフィン', '白色ワセリン', 'Paraffinum Liquidum'] },
  { ja: 'ワセリン', inci: 'Petrolatum', variants: ['白色ワセリン', 'Petroleum Jelly'] },
  { ja: 'パラフィン', inci: 'Paraffin', variants: ['固形パラフィン', 'ハードパラフィン'] },
  { ja: 'セレシン', inci: 'Ceresin', variants: ['セレシンワックス', 'Ceresine'] },
  { ja: 'マイクロクリスタリンワックス', inci: 'Microcrystalline Wax', variants: ['マイクロワックス'] },
  { ja: 'カルナウバロウ', inci: 'Copernicia Cerifera (Carnauba) Wax', variants: ['カルナウバワックス', 'Brazil Wax'] },
  { ja: 'ミツロウ', inci: 'Cera Alba', variants: ['蜜蝋', 'ビーズワックス', 'Beeswax', '白色蜜蝋'] },
  { ja: 'ラノリン', inci: 'Lanolin', variants: ['羊毛脂', '精製ラノリン', 'Wool Fat'] },
  { ja: 'イソノナン酸イソノニル', inci: 'Isononyl Isononanoate', variants: [] },
  { ja: 'カプリル酸カプリン酸トリグリセリド', inci: 'Caprylic/Capric Triglyceride', variants: ['MCTオイル', 'フラクション化ヤシ油', 'GTCC'] },
  { ja: 'エチルヘキサン酸セチル', inci: 'Cetyl Ethylhexanoate', variants: ['オクタン酸セチル'] },
  { ja: 'ジメチコン', inci: 'Dimethicone', variants: ['ポリジメチルシロキサン', 'シリコーン', 'PDMS', 'ジメチルポリシロキサン'] },
  { ja: 'シクロメチコン', inci: 'Cyclomethicone', variants: ['シクロペンタシロキサン'] },
  { ja: 'シクロペンタシロキサン', inci: 'Cyclopentasiloxane', variants: ['D5', 'シクロD5'] },
  { ja: 'フェニルトリメチコン', inci: 'Phenyl Trimethicone', variants: [] },

  // ── 乳化剤・界面活性剤 ──
  { ja: 'ステアリン酸', inci: 'Stearic Acid', variants: [] },
  { ja: 'パルミチン酸', inci: 'Palmitic Acid', variants: [] },
  { ja: 'セテアリルアルコール', inci: 'Cetearyl Alcohol', variants: ['セチルアルコール・ステアリルアルコール混合物'] },
  { ja: 'セチルアルコール', inci: 'Cetyl Alcohol', variants: ['セタノール', 'パルミチルアルコール'] },
  { ja: 'ステアリルアルコール', inci: 'Stearyl Alcohol', variants: [] },
  { ja: 'セテアレス-20', inci: 'Ceteareth-20', variants: [] },
  { ja: 'PEG-40水添ヒマシ油', inci: 'PEG-40 Hydrogenated Castor Oil', variants: ['HCO-40'] },
  { ja: 'ポリソルベート80', inci: 'Polysorbate 80', variants: ['Tween80', 'ポリオキシエチレン(20)ソルビタンモノオレエート'] },
  { ja: 'ポリソルベート20', inci: 'Polysorbate 20', variants: ['Tween20'] },
  { ja: 'レシチン', inci: 'Lecithin', variants: ['大豆レシチン', '卵黄レシチン', 'ホスファチジルコリン'] },
  { ja: 'グリセリル脂肪酸エステル', inci: 'Glyceryl Stearate', variants: ['ステアリン酸グリセリル', 'グリセリルモノステアレート'] },
  { ja: 'ベヘニルアルコール', inci: 'Behenyl Alcohol', variants: ['ドコサノール', '1-ドコサノール'] },
  { ja: 'ラウレス硫酸ナトリウム', inci: 'Sodium Laureth Sulfate', variants: ['SLES', 'ポリオキシエチレンラウリル硫酸ナトリウム'] },
  { ja: 'ラウリル硫酸ナトリウム', inci: 'Sodium Lauryl Sulfate', variants: ['SLS', 'ドデシル硫酸ナトリウム'] },
  { ja: 'コカミドプロピルベタイン', inci: 'Cocamidopropyl Betaine', variants: ['ヤシ油脂肪酸アミドプロピルベタイン', 'CAPB'] },
  { ja: 'コカミドMEA', inci: 'Cocamide MEA', variants: ['ヤシ油脂肪酸モノエタノールアミド'] },

  // ── 増粘剤・安定剤 ──
  { ja: 'カルボマー', inci: 'Carbomer', variants: ['カルボキシビニルポリマー', 'アクリル酸ポリマー', 'CVP'] },
  { ja: 'キサンタンガム', inci: 'Xanthan Gum', variants: ['キサンタン', 'キサンタンゴム'] },
  { ja: 'ヒドロキシエチルセルロース', inci: 'Hydroxyethylcellulose', variants: ['HEC'] },
  { ja: 'ヒドロキシプロピルセルロース', inci: 'Hydroxypropyl Cellulose', variants: ['HPC'] },
  { ja: 'カルボキシメチルセルロースナトリウム', inci: 'Cellulose Gum', variants: ['CMC', 'CMC-Na'] },
  { ja: '寒天', inci: 'Agar', variants: ['アガー'] },
  { ja: 'カラギーナン', inci: 'Carrageenan', variants: ['カラゲナン'] },
  { ja: 'ヒドロキシプロピルグアーガム', inci: 'Hydroxypropyl Guar', variants: [] },
  { ja: 'アクリレーツコポリマー', inci: 'Acrylates Copolymer', variants: [] },

  // ── 保湿成分・機能性成分 ──
  { ja: 'ヒアルロン酸Na', inci: 'Sodium Hyaluronate', variants: ['ヒアルロン酸ナトリウム', 'ヒアルロン酸', 'Hyaluronic Acid', 'HA'] },
  { ja: 'コラーゲン', inci: 'Soluble Collagen', variants: ['可溶性コラーゲン', '水溶性コラーゲン', 'コラーゲンペプチド'] },
  { ja: 'エラスチン', inci: 'Hydrolyzed Elastin', variants: ['加水分解エラスチン'] },
  { ja: 'セラミドNP', inci: 'Ceramide NP', variants: ['セラミド2', 'Ceramide 2', 'セラミドII'] },
  { ja: 'セラミドAP', inci: 'Ceramide AP', variants: ['セラミド6II', 'Ceramide 6II'] },
  { ja: 'セラミドEOP', inci: 'Ceramide EOP', variants: ['セラミド1', 'Ceramide 1'] },
  { ja: 'スフィンゴ糖脂質', inci: 'Glycosphingolipids', variants: ['糖セラミド'] },
  { ja: 'ナイアシンアミド', inci: 'Niacinamide', variants: ['ニコチン酸アミド', 'ビタミンB3', 'Nicotinamide'] },
  { ja: 'アスコルビン酸', inci: 'Ascorbic Acid', variants: ['ビタミンC', 'L-アスコルビン酸'] },
  { ja: 'アスコルビン酸グルコシド', inci: 'Ascorbyl Glucoside', variants: ['アスコルビルグルコシド', 'AA-2G'] },
  { ja: 'リン酸L-アスコルビルMg', inci: 'Magnesium Ascorbyl Phosphate', variants: ['リン酸アスコルビルマグネシウム', 'MAP'] },
  { ja: 'レチノール', inci: 'Retinol', variants: ['ビタミンA', 'Vitamin A'] },
  { ja: 'パルミチン酸レチニル', inci: 'Retinyl Palmitate', variants: ['レチノールパルミテート'] },
  { ja: 'トコフェロール', inci: 'Tocopherol', variants: ['ビタミンE', 'α-トコフェロール', 'dl-α-トコフェロール'] },
  { ja: '酢酸トコフェロール', inci: 'Tocopheryl Acetate', variants: ['ビタミンE酢酸エステル', 'dl-α-トコフェリルアセテート'] },
  { ja: 'パンテノール', inci: 'Panthenol', variants: ['D-パンテノール', 'プロビタミンB5', 'パントテノール'] },
  { ja: 'アラントイン', inci: 'Allantoin', variants: ['アラントイン（グリコール酸） ジウレア'] },
  { ja: 'ビサボロール', inci: 'Bisabolol', variants: ['α-ビサボロール', 'Bisabolol'] },
  { ja: 'グルコン酸亜鉛', inci: 'Zinc Gluconate', variants: [] },
  { ja: 'レゾルシノール', inci: 'Resorcinol', variants: ['m-ジヒドロキシベンゼン'] },
  { ja: 'カフェイン', inci: 'Caffeine', variants: ['無水カフェイン'] },

  // ── 防腐剤・抗菌剤 ──
  { ja: 'フェノキシエタノール', inci: 'Phenoxyethanol', variants: ['エチレングリコールモノフェニルエーテル'] },
  { ja: 'メチルパラベン', inci: 'Methylparaben', variants: ['パラオキシ安息香酸メチル', '4-ヒドロキシ安息香酸メチル'] },
  { ja: 'エチルパラベン', inci: 'Ethylparaben', variants: ['パラオキシ安息香酸エチル'] },
  { ja: 'プロピルパラベン', inci: 'Propylparaben', variants: ['パラオキシ安息香酸プロピル'] },
  { ja: 'ブチルパラベン', inci: 'Butylparaben', variants: ['パラオキシ安息香酸ブチル'] },
  { ja: '安息香酸Na', inci: 'Sodium Benzoate', variants: ['安息香酸ナトリウム'] },
  { ja: 'ソルビン酸K', inci: 'Potassium Sorbate', variants: ['ソルビン酸カリウム'] },
  { ja: 'クロルヘキシジン', inci: 'Chlorhexidine', variants: ['塩酸クロルヘキシジン', 'グルコン酸クロルヘキシジン'] },
  { ja: '塩化ベンザルコニウム', inci: 'Benzalkonium Chloride', variants: ['BAC', '逆性石けん'] },
  { ja: 'エチルヘキシルグリセリン', inci: 'Ethylhexylglycerin', variants: ['オクタン酸グリセリン誘導体'] },
  { ja: 'カプリリルグリコール', inci: 'Caprylyl Glycol', variants: ['オクタン-1,2-ジオール'] },

  // ── pH調整剤 ──
  { ja: 'クエン酸', inci: 'Citric Acid', variants: ['無水クエン酸'] },
  { ja: 'クエン酸Na', inci: 'Sodium Citrate', variants: ['クエン酸ナトリウム'] },
  { ja: '乳酸', inci: 'Lactic Acid', variants: ['L-乳酸', 'DL-乳酸'] },
  { ja: '乳酸Na', inci: 'Sodium Lactate', variants: ['乳酸ナトリウム'] },
  { ja: '水酸化Na', inci: 'Sodium Hydroxide', variants: ['水酸化ナトリウム', '苛性ソーダ', 'NaOH'] },
  { ja: 'トリエタノールアミン', inci: 'Triethanolamine', variants: ['TEA', 'トリオールアミン'] },
  { ja: 'アルギニン', inci: 'Arginine', variants: ['L-アルギニン', '塩基性アミノ酸'] },

  // ── 紫外線吸収剤・散乱剤 ──
  { ja: 'エチルヘキシルメトキシシンナメート', inci: 'Ethylhexyl Methoxycinnamate', variants: ['オクチルメトキシシンナメート', 'OMC'] },
  { ja: 'ベンゾフェノン-4', inci: 'Benzophenone-4', variants: ['スルホイソベンゾフェノン', 'BP-4'] },
  { ja: 'ビスエチルヘキシルオキシフェノールメトキシフェニルトリアジン', inci: 'Bis-Ethylhexyloxyphenol Methoxyphenyl Triazine', variants: ['Tinosorb S'] },
  { ja: '酸化チタン', inci: 'Titanium Dioxide', variants: ['二酸化チタン', 'CI 77891', '微粒子酸化チタン'] },
  { ja: '酸化亜鉛', inci: 'Zinc Oxide', variants: ['亜鉛華', 'CI 77947', '微粒子酸化亜鉛'] },
  { ja: 'オクトクリレン', inci: 'Octocrylene', variants: [] },

  // ── 着色料 ──
  { ja: '酸化鉄', inci: 'Iron Oxides', variants: ['ベンガラ', 'CI 77491', 'CI 77492', 'CI 77499', '酸化鉄（赤）', '酸化鉄（黄）', '酸化鉄（黒）'] },
  { ja: 'タルク', inci: 'Talc', variants: ['タルク（複合粉体）', 'CI 77718'] },
  { ja: 'マイカ', inci: 'Mica', variants: ['雲母', 'CI 77019'] },
  { ja: 'カオリン', inci: 'Kaolin', variants: ['白色カオリン', 'チャイナクレー'] },
  { ja: '黄酸化鉄', inci: 'CI 77492', variants: ['Iron Oxide Yellow'] },
  { ja: '赤色226号', inci: 'CI 12085', variants: ['D&C Red No.6'] },
  { ja: '青色1号', inci: 'CI 42090', variants: ['FD&C Blue No.1', 'ブリリアントブルーFCF'] },

  // ── 植物エキス ──
  { ja: 'アロエベラ葉エキス', inci: 'Aloe Barbadensis Leaf Extract', variants: ['アロエエキス', 'アロエ液汁'] },
  { ja: 'カミツレ花エキス', inci: 'Chamomilla Recutita (Matricaria) Flower Extract', variants: ['カモミールエキス', 'カミルレエキス'] },
  { ja: 'センテラアジアチカエキス', inci: 'Centella Asiatica Extract', variants: ['ツボクサエキス', 'CICA', 'シカエキス'] },
  { ja: 'ユーカリ葉エキス', inci: 'Eucalyptus Globulus Leaf Extract', variants: ['ユーカリエキス'] },
  { ja: 'ラベンダー花エキス', inci: 'Lavandula Angustifolia (Lavender) Flower Extract', variants: ['ラベンダーエキス'] },
  { ja: '緑茶エキス', inci: 'Camellia Sinensis Leaf Extract', variants: ['チャ葉エキス', 'グリーンティーエキス'] },
  { ja: 'バーチ樹皮エキス', inci: 'Betula Alba Bark Extract', variants: ['白樺エキス', 'ビルベリーエキス'] },
  { ja: 'リコリスエキス', inci: 'Glycyrrhiza Glabra (Licorice) Root Extract', variants: ['カンゾウエキス', 'グリチルリチン酸関連'] },
  { ja: 'グリチルリチン酸2K', inci: 'Dipotassium Glycyrrhizate', variants: ['グリチルリチン酸ジカリウム'] },
  { ja: 'フラーレン', inci: 'Fullerene', variants: ['C60', 'バックミンスターフラーレン'] },

  // ── 香料・精油 ──
  { ja: '香料', inci: 'Fragrance', variants: ['Parfum', 'フレグランス', '調合香料', '天然香料', '合成香料'] },
  { ja: 'ラベンダー油', inci: 'Lavandula Angustifolia (Lavender) Oil', variants: ['ラベンダーオイル', 'ラベンダー精油'] },
  { ja: 'ローズマリー葉油', inci: 'Rosmarinus Officinalis (Rosemary) Leaf Oil', variants: ['ローズマリーオイル'] },
  { ja: 'ティーツリー葉油', inci: 'Melaleuca Alternifolia (Tea Tree) Leaf Oil', variants: ['ティーツリーオイル'] },
  { ja: 'ペパーミント油', inci: 'Mentha Piperita (Peppermint) Oil', variants: ['ハッカ油', 'ペパーミントオイル'] },

  // ── 追加：保湿成分 ──
  { ja: 'エリスリトール', inci: 'Erythritol', variants: ['エリスリット'] },
  { ja: 'トレハロース', inci: 'Trehalose', variants: ['α,α-トレハロース'] },
  { ja: 'ソルビトール', inci: 'Sorbitol', variants: ['D-ソルビトール', 'グルシトール', 'D-グルシトール'] },
  { ja: 'マンニトール', inci: 'Mannitol', variants: ['D-マンニトール', 'マンニット'] },
  { ja: 'キシリトール', inci: 'Xylitol', variants: ['D-キシリトール'] },
  { ja: 'イノシトール', inci: 'Inositol', variants: ['myo-イノシトール'] },
  { ja: 'ポリグルタミン酸', inci: 'Polyglutamic Acid', variants: ['γ-ポリグルタミン酸', 'PGA', 'ポリグルタミン酸Na'] },
  { ja: 'ベタイン', inci: 'Betaine', variants: ['トリメチルグリシン', 'TMG', 'アミノ酸ベタイン'] },
  { ja: 'セリン', inci: 'Serine', variants: ['L-セリン', 'アミノ酸'] },
  { ja: 'グルタミン酸', inci: 'Glutamic Acid', variants: ['L-グルタミン酸'] },
  { ja: 'プロリン', inci: 'Proline', variants: ['L-プロリン'] },
  { ja: 'スレオニン', inci: 'Threonine', variants: ['L-スレオニン', 'L-トレオニン'] },
  { ja: 'ピロリドンカルボン酸Na', inci: 'Sodium PCA', variants: ['ピロリドンカルボン酸ナトリウム', 'PCA-Na', 'NaPCA'] },
  { ja: 'ヒアルロン酸', inci: 'Hyaluronic Acid', variants: ['ヒアルロン酸（高分子）', 'HA'] },
  { ja: '加水分解ヒアルロン酸', inci: 'Hydrolyzed Hyaluronic Acid', variants: ['低分子ヒアルロン酸', '加水分解HA'] },
  { ja: 'アセチルヒアルロン酸Na', inci: 'Sodium Acetylated Hyaluronate', variants: ['スーパーヒアルロン酸', 'アセチル化ヒアルロン酸'] },
  { ja: 'リピジュア', inci: 'Polyquaternium-51', variants: ['ポリクオタニウム-51', '2-メタクロイルオキシエチルホスホリルコリン重合体'] },
  { ja: 'アミノ酸系保湿成分', inci: 'Amino Acids', variants: ['複合アミノ酸'] },
  { ja: 'ポリエチレングリコール', inci: 'PEG-8', variants: ['PEG', 'マクロゴール', 'ポリエチレングリコール400'] },
  { ja: 'グリコーゲン', inci: 'Glycogen', variants: ['動物性デンプン'] },
  { ja: 'コンドロイチン硫酸Na', inci: 'Sodium Chondroitin Sulfate', variants: ['コンドロイチン硫酸ナトリウム'] },

  // ── 追加：油性成分 ──
  { ja: 'マカデミア種子油', inci: 'Macadamia Ternifolia Seed Oil', variants: ['マカデミアナッツ油', 'マカデミアオイル'] },
  { ja: 'アボカド油', inci: 'Persea Gratissima (Avocado) Oil', variants: ['アボカドオイル'] },
  { ja: 'スイートアーモンド油', inci: 'Prunus Amygdalus Dulcis (Sweet Almond) Oil', variants: ['アーモンド油', 'スイートアーモンドオイル'] },
  { ja: 'グレープシード油', inci: 'Vitis Vinifera (Grape) Seed Oil', variants: ['グレープシードオイル', 'ブドウ種子油'] },
  { ja: 'ハイドロゲネイテッドポリデセン', inci: 'Hydrogenated Polydecene', variants: ['水添ポリデセン'] },
  { ja: 'イソドデカン', inci: 'Isododecane', variants: [] },
  { ja: 'イソヘキサデカン', inci: 'Isohexadecane', variants: [] },
  { ja: 'ミリスチン酸イソプロピル', inci: 'Isopropyl Myristate', variants: ['IPM', 'ミリスチン酸イソプロピルエステル'] },
  { ja: 'パルミチン酸イソプロピル', inci: 'Isopropyl Palmitate', variants: ['IPP'] },
  { ja: 'パルミチン酸エチルヘキシル', inci: 'Ethylhexyl Palmitate', variants: ['パルミチン酸2-エチルヘキシル', 'EHP'] },
  { ja: 'ステアリン酸エチルヘキシル', inci: 'Ethylhexyl Stearate', variants: ['ステアリン酸2-エチルヘキシル'] },
  { ja: 'オレイン酸エチルヘキシル', inci: 'Ethylhexyl Oleate', variants: [] },
  { ja: 'ジカプリリルカーボネート', inci: 'Dicaprylyl Carbonate', variants: [] },
  { ja: 'ジカプリリルエーテル', inci: 'Dicaprylyl Ether', variants: [] },
  { ja: 'ネオペンチルグリコールジカプリレート/ジカプレート', inci: 'Neopentyl Glycol Dicaprate', variants: [] },
  { ja: 'トリ(カプリル酸/カプリン酸)グリセリル', inci: 'Glyceryl Tricaprylate/Tricaprate', variants: ['GTリシノール', 'トリカプリリン'] },
  { ja: 'ラウリン酸ヘキシル', inci: 'Hexyl Laurate', variants: [] },
  { ja: 'セバシン酸ジエチル', inci: 'Diethyl Sebacate', variants: [] },
  { ja: 'コメヌカ油', inci: 'Oryza Sativa (Rice) Bran Oil', variants: ['米ぬか油', 'ライスブランオイル'] },
  { ja: 'コムギ胚芽油', inci: 'Triticum Vulgare (Wheat) Germ Oil', variants: ['小麦胚芽油', 'ウィートジャームオイル'] },
  { ja: 'ツバキ種子油', inci: 'Camellia Japonica Seed Oil', variants: ['椿油', 'カメリアオイル'] },
  { ja: '月見草油', inci: 'Oenothera Biennis (Evening Primrose) Oil', variants: ['イブニングプリムローズオイル'] },
  { ja: '亜麻仁油', inci: 'Linum Usitatissimum (Linseed) Seed Oil', variants: ['フラックスシードオイル', '亜麻仁油'] },
  { ja: 'ゴマ油', inci: 'Sesamum Indicum (Sesame) Seed Oil', variants: ['セサミオイル', '胡麻油'] },

  // ── 追加：界面活性剤 ──
  { ja: 'ラウロイルグルタミン酸ジ（フィトステリル/オクチルドデシル）', inci: 'Diisostearoyl Trimethylolpropane Siloxy Silicate', variants: ['エルデュウPS-203'] },
  { ja: 'PEG-60水添ヒマシ油', inci: 'PEG-60 Hydrogenated Castor Oil', variants: ['HCO-60', 'ポリオキシエチレン(60)水素添加ヒマシ油'] },
  { ja: 'PEG-20水添ヒマシ油', inci: 'PEG-20 Hydrogenated Castor Oil', variants: ['HCO-20'] },
  { ja: 'ポリグリセリル-10ステアレート', inci: 'Polyglyceryl-10 Stearate', variants: [] },
  { ja: 'ポリグリセリル-10ラウレート', inci: 'Polyglyceryl-10 Laurate', variants: [] },
  { ja: 'ポリグリセリル-2ジポリヒドロキシステアレート', inci: 'Polyglyceryl-2 Dipolyhydroxystearate', variants: [] },
  { ja: 'PEG-9ポリジメチルシロキシエチルジメチコン', inci: 'PEG-9 Polydimethylsiloxyethyl Dimethicone', variants: ['シリコーン系乳化剤'] },
  { ja: 'スクロースステアレート', inci: 'Sucrose Stearate', variants: ['蔗糖ステアリン酸エステル', 'ショ糖脂肪酸エステル'] },
  { ja: 'スクロースラウレート', inci: 'Sucrose Laurate', variants: ['蔗糖ラウリン酸エステル'] },
  { ja: 'ソルビタンセスキオレエート', inci: 'Sorbitan Sesquioleate', variants: [] },
  { ja: 'ソルビタンモノオレエート', inci: 'Sorbitan Oleate', variants: ['Span80'] },
  { ja: 'ソルビタンモノステアレート', inci: 'Sorbitan Stearate', variants: ['Span60'] },
  { ja: 'ポリソルベート60', inci: 'Polysorbate 60', variants: ['Tween60'] },
  { ja: 'コカミドDEA', inci: 'Cocamide DEA', variants: ['ヤシ油脂肪酸ジエタノールアミド'] },
  { ja: 'ラウラミドDEA', inci: 'Lauramide DEA', variants: ['ラウリン酸ジエタノールアミド'] },
  { ja: 'ラウラミドMEA', inci: 'Lauramide MEA', variants: ['ラウリン酸モノエタノールアミド'] },
  { ja: 'ラウリルグルコシド', inci: 'Lauryl Glucoside', variants: ['デシルグルコシドと混合も可', 'アルキルグルコシド'] },
  { ja: 'デシルグルコシド', inci: 'Decyl Glucoside', variants: ['アルキルポリグルコシド'] },
  { ja: 'コカミドプロピルヒドロキシスルタイン', inci: 'Cocamidopropyl Hydroxysultaine', variants: [] },
  { ja: 'ラウリミノジプロピオン酸Na', inci: 'Sodium Lauriminodipropionate', variants: [] },
  { ja: 'ジメチルラウラミン', inci: 'Dimethyl Lauramine', variants: [] },
  { ja: 'ステアロイルグルタミン酸Na', inci: 'Sodium Stearoyl Glutamate', variants: ['ステアロイルグルタミン酸ナトリウム'] },
  { ja: 'ラウロイルグルタミン酸Na', inci: 'Sodium Lauroyl Glutamate', variants: ['ラウロイルグルタミン酸ナトリウム'] },
  { ja: 'コカミドプロピルジメチルアミン', inci: 'Cocamidopropyl Dimethylamine', variants: [] },
  { ja: 'セテアリル硫酸ナトリウム', inci: 'Sodium Cetearyl Sulfate', variants: [] },

  // ── 追加：増粘剤 ──
  { ja: 'アクリル酸Naクロスポリマー', inci: 'Sodium Acrylates Crosspolymer', variants: ['架橋型アクリル酸ナトリウム'] },
  { ja: 'アクリレーツ/C10-30アルキルアクリレートクロスポリマー', inci: 'Acrylates/C10-30 Alkyl Acrylate Crosspolymer', variants: ['アルキルアクリレートクロスポリマー', 'Pemulen'] },
  { ja: 'ポリアクリルアミド', inci: 'Polyacrylamide', variants: ['アクリルアミドポリマー'] },
  { ja: 'ヒドロキシプロピルメチルセルロース', inci: 'Hydroxypropyl Methylcellulose', variants: ['HPMC', 'ヒプロメロース'] },
  { ja: 'メチルセルロース', inci: 'Methylcellulose', variants: ['MC'] },
  { ja: 'ローカストビーンガム', inci: 'Locust Bean Gum', variants: ['イナゴマメガム', 'カロブガム'] },
  { ja: 'グアーガム', inci: 'Guar Gum', variants: ['グアール豆ガム'] },
  { ja: 'トラガントガム', inci: 'Tragacanth Gum', variants: ['トラガカントガム'] },
  { ja: 'アラビアガム', inci: 'Acacia Senegal Gum', variants: ['アカシアガム', 'アラビアゴム'] },
  { ja: 'ジェランガム', inci: 'Gellan Gum', variants: [] },
  { ja: 'スクレロチウムガム', inci: 'Sclerotium Gum', variants: [] },
  { ja: 'プルラン', inci: 'Pullulan', variants: ['プルラン（多糖類）'] },
  { ja: 'デキストリン', inci: 'Dextrin', variants: ['デキストリン（粉末）'] },
  { ja: 'デキストラン', inci: 'Dextran', variants: [] },
  { ja: 'ポリビニルアルコール', inci: 'Polyvinyl Alcohol', variants: ['PVA'] },
  { ja: 'ポリビニルピロリドン', inci: 'PVP', variants: ['ポリビニルピロリドン', 'Polyvinylpyrrolidone'] },
  { ja: 'カルボキシビニルポリマー', inci: 'Carbomer', variants: ['Carbopol', 'CVP', 'アクリル酸重合体'] },
  { ja: 'ヒドロキシエチルアクリレート/アクリロイルジメチルタウリンNaコポリマー', inci: 'Hydroxyethyl Acrylate/Sodium Acryloyldimethyl Taurate Copolymer', variants: ['Simulgel NS'] },
  { ja: 'ベントナイト', inci: 'Bentonite', variants: ['モンモリロナイト', '膨潤性粘土鉱物'] },
  { ja: 'ヘクトライト', inci: 'Hectorite', variants: [] },

  // ── 追加：美容成分（植物エキス） ──
  { ja: 'サクラ葉エキス', inci: 'Prunus Serrulata Leaf Extract', variants: ['桜葉エキス'] },
  { ja: 'サクラ花エキス', inci: 'Prunus Serrulata Flower Extract', variants: ['桜花エキス', 'サクラエキス'] },
  { ja: 'ダマスクバラ花エキス', inci: 'Rosa Damascena Flower Extract', variants: ['ローズエキス', 'バラ花エキス'] },
  { ja: 'ダマスクバラ花水', inci: 'Rosa Damascena Flower Water', variants: ['ローズウォーター', 'バラ水'] },
  { ja: 'シャクヤク根エキス', inci: 'Paeonia Lactiflora Root Extract', variants: ['芍薬エキス', 'ペオニアエキス'] },
  { ja: 'コウジ酸', inci: 'Kojic Acid', variants: ['コウジ酸（美白成分）'] },
  { ja: 'アルブチン', inci: 'Arbutin', variants: ['α-アルブチン', 'β-アルブチン'] },
  { ja: '4-メトキシサリチル酸カリウム塩', inci: 'Potassium 4-Methoxysalicylate', variants: ['4MSK', 'カリウム塩型美白剤'] },
  { ja: 'トラネキサム酸', inci: 'Tranexamic Acid', variants: ['トラネキサム酸（美白成分）', 't-AMCHA'] },
  { ja: 'ハイドロキノン', inci: 'Hydroquinone', variants: ['ヒドロキノン', 'キノン系美白剤'] },
  { ja: 'レゾルシノール', inci: 'Resorcinol', variants: ['レソルシン', 'm-ジヒドロキシベンゼン'] },
  { ja: 'ビタミンC誘導体（リン酸型）', inci: 'Sodium Ascorbyl Phosphate', variants: ['アスコルビルリン酸Na', 'SAP'] },
  { ja: 'ツバキ花エキス', inci: 'Camellia Japonica Flower Extract', variants: ['椿花エキス'] },
  { ja: 'コメエキス', inci: 'Oryza Sativa (Rice) Extract', variants: ['米エキス', 'ライスエキス'] },
  { ja: 'コメ発酵液', inci: 'Oryza Sativa (Rice) Ferment Filtrate', variants: ['酒粕エキス', '米発酵エキス', '清酒エキス'] },
  { ja: '加水分解コメタンパク', inci: 'Hydrolyzed Rice Protein', variants: ['コメ加水分解タンパク', '米タンパク'] },
  { ja: 'マルトース', inci: 'Maltose', variants: ['麦芽糖'] },
  { ja: 'ぶどうエキス', inci: 'Vitis Vinifera (Grape) Fruit Extract', variants: ['グレープエキス'] },
  { ja: 'ぶどう種子エキス', inci: 'Vitis Vinifera (Grape) Seed Extract', variants: ['グレープシードエキス', 'OPC'] },
  { ja: 'ポメグラネートエキス', inci: 'Punica Granatum Fruit Extract', variants: ['ザクロエキス', 'ポメグラネート'] },
  { ja: 'ブルーベリー葉エキス', inci: 'Vaccinium Angustifolium (Blueberry) Leaf Extract', variants: ['ブルーベリーエキス'] },
  { ja: 'カカオ種子エキス', inci: 'Theobroma Cacao (Cocoa) Seed Extract', variants: ['カカオエキス', 'ニブスエキス'] },
  { ja: 'コーヒー種子エキス', inci: 'Coffea Arabica (Coffee) Seed Extract', variants: ['コーヒーエキス', 'カフェーオイル'] },
  { ja: 'シソ葉エキス', inci: 'Perilla Ocymoides Leaf Extract', variants: ['紫蘇エキス', 'ペリラエキス'] },
  { ja: 'ドクダミエキス', inci: 'Houttuynia Cordata Extract', variants: ['どくだみエキス'] },
  { ja: 'ハトムギ種子エキス', inci: 'Coix Lacryma-Jobi Ma-Yuen Seed Extract', variants: ['ヨクイニンエキス', '薏苡仁エキス'] },
  { ja: 'オウゴン根エキス', inci: 'Scutellaria Baicalensis Root Extract', variants: ['黄芩エキス', 'バイカリンエキス'] },
  { ja: 'クワ根皮エキス', inci: 'Morus Alba Root Extract', variants: ['桑白皮エキス', 'マルベリーエキス'] },
  { ja: 'ニンジン根エキス', inci: 'Daucus Carota Sativa (Carrot) Root Extract', variants: ['キャロットエキス', 'ニンジンエキス'] },
  { ja: '高麗人参エキス', inci: 'Panax Ginseng Root Extract', variants: ['人参エキス', 'ジンセンエキス', 'パナックスジンセンエキス'] },
  { ja: 'イチョウ葉エキス', inci: 'Ginkgo Biloba Leaf Extract', variants: ['銀杏葉エキス', 'ギンコエキス'] },
  { ja: 'ウコン根茎エキス', inci: 'Curcuma Longa (Turmeric) Root Extract', variants: ['ターメリックエキス', 'クルクミンエキス'] },
  { ja: 'ショウガ根エキス', inci: 'Zingiber Officinale (Ginger) Root Extract', variants: ['ジンジャーエキス', '生姜エキス'] },
  { ja: 'オリーブ葉エキス', inci: 'Olea Europaea (Olive) Leaf Extract', variants: ['オリーブエキス', 'オレウロペインエキス'] },
  { ja: 'ロスマリン酸', inci: 'Rosmarinic Acid', variants: ['ローズマリー酸'] },
  { ja: 'ルスクス根エキス', inci: 'Ruscus Aculeatus Root Extract', variants: ['ブッチャーズブルームエキス'] },
  { ja: 'ホップ球果エキス', inci: 'Humulus Lupulus (Hops) Cone Extract', variants: ['ホップエキス'] },
  { ja: 'マロニエ種子エキス', inci: 'Aesculus Hippocastanum (Horse Chestnut) Seed Extract', variants: ['トチノキエキス', 'エスシンエキス'] },
  { ja: 'ヘーゼルナッツ種子エキス', inci: 'Corylus Avellana (Hazel) Seed Extract', variants: ['ヘーゼルナッツエキス'] },
  { ja: 'シラカバ樹液', inci: 'Betula Alba Juice', variants: ['白樺樹液', 'バーチジュース'] },
  { ja: 'アルニカ花エキス', inci: 'Arnica Montana Flower Extract', variants: ['アルニカエキス'] },
  { ja: 'カレンデュラ花エキス', inci: 'Calendula Officinalis Flower Extract', variants: ['金盞花エキス', 'マリーゴールドエキス'] },
  { ja: 'エキナセアエキス', inci: 'Echinacea Purpurea Extract', variants: ['エキナシアエキス'] },
  { ja: 'マテ葉エキス', inci: 'Ilex Paraguariensis Leaf Extract', variants: ['マテエキス'] },
  { ja: 'キャベツエキス', inci: 'Brassica Oleracea Capitata Leaf Extract', variants: ['キャベツ葉エキス'] },
  { ja: 'モリンガ種子エキス', inci: 'Moringa Oleifera Seed Extract', variants: ['モリンガエキス'] },

  // ── 追加：美容成分（機能性） ──
  { ja: 'コエンザイムQ10', inci: 'Ubiquinone', variants: ['ユビキノン', 'CoQ10'] },
  { ja: 'グルコシルセラミド', inci: 'Glucosylceramide', variants: ['フィトスフィンゴシン誘導体'] },
  { ja: 'フィトスフィンゴシン', inci: 'Phytosphingosine', variants: [] },
  { ja: 'アデノシン', inci: 'Adenosine', variants: ['アデノシン（機能性成分）'] },
  { ja: 'デヒドロアセテートNa', inci: 'Sodium Dehydroacetate', variants: ['デヒドロ酢酸ナトリウム', 'DHA-Na'] },
  { ja: 'オリゴペプチド-1', inci: 'Oligopeptide-1', variants: ['EGF', '上皮細胞成長因子'] },
  { ja: '加水分解コラーゲン', inci: 'Hydrolyzed Collagen', variants: ['コラーゲンペプチド', '加水分解コラーゲンペプチド'] },
  { ja: '加水分解シルク', inci: 'Hydrolyzed Silk', variants: ['シルクペプチド', '絹タンパク'] },
  { ja: '加水分解ケラチン', inci: 'Hydrolyzed Keratin', variants: ['ケラチンペプチド'] },
  { ja: 'トリペプチド-1銅', inci: 'Copper Tripeptide-1', variants: ['GHK-Cu', '銅ペプチド'] },
  { ja: 'アセチルテトラペプチド-2', inci: 'Acetyl Tetrapeptide-2', variants: [] },
  { ja: 'パルミトイルトリペプチド-1', inci: 'Palmitoyl Tripeptide-1', variants: [] },
  { ja: 'パルミトイルテトラペプチド-7', inci: 'Palmitoyl Tetrapeptide-7', variants: [] },
  { ja: 'レチニルアセテート', inci: 'Retinyl Acetate', variants: ['酢酸レチノール'] },
  { ja: 'レチナール', inci: 'Retinal', variants: ['レチノアール', 'アルデヒド型ビタミンA'] },
  { ja: 'レチノイン酸', inci: 'Retinoic Acid', variants: ['トレチノイン', 'ビタミンA酸'] },
  { ja: 'テトラヘキシルデカン酸アスコルビル', inci: 'Ascorbyl Tetraisopalmitate', variants: ['ATIP', '油溶性ビタミンC誘導体'] },
  { ja: '3-O-エチルアスコルビン酸', inci: '3-O-Ethyl Ascorbic Acid', variants: ['3-Oエチルアスコルビン酸', 'エチルアスコルビン酸'] },
  { ja: 'ヘスペリジン', inci: 'Hesperidin', variants: ['ビタミンP', 'ルチン類似'] },
  { ja: 'ルチン', inci: 'Rutin', variants: ['ビタミンP（ルチン）', 'ルチン（配糖体）'] },
  { ja: 'ケルセチン', inci: 'Quercetin', variants: ['ケルセチン（フラボノイド）'] },
  { ja: 'レスベラトロール', inci: 'Resveratrol', variants: [] },
  { ja: 'グルタチオン', inci: 'Glutathione', variants: ['還元型グルタチオン'] },
  { ja: 'α-リポ酸', inci: 'Thioctic Acid', variants: ['チオクト酸', 'アルファリポ酸'] },
  { ja: 'N-アセチルグルコサミン', inci: 'Glucosamine HCl', variants: ['N-アセチル-D-グルコサミン', 'NAG'] },
  { ja: 'ヒドロキシプロリン', inci: 'Hydroxyproline', variants: ['L-ヒドロキシプロリン'] },
  { ja: 'スーパーオキシドジスムターゼ', inci: 'Superoxide Dismutase', variants: ['SOD'] },
  { ja: 'カタラーゼ', inci: 'Catalase', variants: [] },
  { ja: 'リゾホスファチジン酸', inci: 'Lysophosphatidic Acid', variants: ['LPA'] },

  // ── 追加：紫外線吸収剤 ──
  { ja: 'ジエチルアミノヒドロキシベンゾイル安息香酸ヘキシル', inci: 'Diethylamino Hydroxybenzoyl Hexyl Benzoate', variants: ['DHHB', 'Uvinul A Plus'] },
  { ja: 'ブチルメトキシジベンゾイルメタン', inci: 'Butyl Methoxydibenzoylmethane', variants: ['アボベンゾン', 'Parsol 1789'] },
  { ja: 'ベンゾフェノン-3', inci: 'Benzophenone-3', variants: ['オキシベンゾン', 'BP-3'] },
  { ja: 'メトキシケイヒ酸オクチル', inci: 'Octyl Methoxycinnamate', variants: ['OMC', 'パルソールMCX'] },
  { ja: 'サリチル酸エチルヘキシル', inci: 'Ethylhexyl Salicylate', variants: ['オクチルサリシレート'] },
  { ja: 'ホモサレート', inci: 'Homosalate', variants: ['ホモメンチルサリシレート'] },
  { ja: 'エカムスール', inci: 'Ecamsule', variants: ['メキソリル SX', 'テレフタリリデンジカンフルスルホン酸'] },
  { ja: 'メチレンビスベンゾトリアゾリルテトラメチルブチルフェノール', inci: 'Methylene Bis-Benzotriazolyl Tetramethylbutylphenol', variants: ['Tinosorb M', 'ビスオクトリゾール'] },
  { ja: 'フェニルベンズイミダゾールスルホン酸', inci: 'Phenylbenzimidazole Sulfonic Acid', variants: ['エンシュルス'] },
  { ja: 'ジオクチルブタミドトリアゾン', inci: 'Dioctyl Butamido Triazone', variants: ['UVAフィルター'] },
  { ja: 'ポリシリコーン-15', inci: 'Polysilicone-15', variants: ['ジメチコジエチルベンザルマロナートポリマー', 'Parsol SLX'] },

  // ── 追加：紫外線散乱剤・パウダー ──
  { ja: '表面処理酸化チタン', inci: 'Titanium Dioxide (and) Silica', variants: ['シリカコート酸化チタン', '疎水化酸化チタン'] },
  { ja: '表面処理酸化亜鉛', inci: 'Zinc Oxide (and) Triethoxycaprylylsilane', variants: ['シリコーン処理酸化亜鉛'] },
  { ja: 'シリカ', inci: 'Silica', variants: ['二酸化ケイ素', 'SiO2', 'シリカ球状粉体'] },
  { ja: 'ナイロン-12', inci: 'Nylon-12', variants: ['ポリアミド12', 'ナイロンパウダー'] },
  { ja: 'ポリメチルメタクリレート', inci: 'Polymethylmethacrylate', variants: ['PMMA', 'アクリルパウダー'] },
  { ja: 'セリサイト', inci: 'Sericite', variants: ['絹雲母', '金雲母'] },
  { ja: 'ウルトラマリン', inci: 'Ultramarines', variants: ['群青', 'CI 77007'] },
  { ja: 'マンガンバイオレット', inci: 'Manganese Violet', variants: ['CI 77742'] },
  { ja: 'クロム酸化物グリーン', inci: 'Chromium Oxide Greens', variants: ['CI 77288', '酸化クロム'] },
  { ja: 'フェリックアンモニウムフェロシアニド', inci: 'Ferric Ammonium Ferrocyanide', variants: ['CI 77510', '紺青'] },
  { ja: 'カーボンブラック', inci: 'Carbon Black', variants: ['CI 77266', '黒色401号'] },

  // ── 追加：着色料・色素 ──
  { ja: '赤色201号', inci: 'CI 15850', variants: ['D&C Red 7', 'リソールルビンB'] },
  { ja: '赤色202号', inci: 'CI 15850:1', variants: ['D&C Red 6', 'リソールルビンBCa'] },
  { ja: '赤色204号', inci: 'CI 15800', variants: [] },
  { ja: '赤色223号', inci: 'CI 45380', variants: ['D&C Red 21', 'テトラブロムフルオレッセイン'] },
  { ja: '赤色505号', inci: 'CI 73360', variants: [] },
  { ja: '橙色205号', inci: 'CI 45370', variants: ['D&C Orange 5'] },
  { ja: '黄色4号', inci: 'CI 19140', variants: ['タートラジン', 'FD&C Yellow 5'] },
  { ja: '黄色5号', inci: 'CI 15985', variants: ['サンセットイエローFCF', 'FD&C Yellow 6'] },
  { ja: '青色2号', inci: 'CI 73015', variants: ['インジゴカルミン', 'FD&C Blue 2'] },
  { ja: '緑色3号', inci: 'CI 42053', variants: ['ファストグリーンFCF', 'FD&C Green 3'] },
  { ja: '赤色3号', inci: 'CI 45430', variants: ['エリスロシン', 'FD&C Red 3'] },

  // ── 追加：医薬部外品有効成分 ──
  { ja: 'グリチルレチン酸ステアリル', inci: 'Stearyl Glycyrrhetinate', variants: ['ステアリルグリチルリチネート'] },
  { ja: 'グリチルリチン酸アンモニウム', inci: 'Ammonium Glycyrrhizate', variants: ['グリチルリチン酸アンモニウム塩'] },
  { ja: 'ε-アミノカプロン酸', inci: 'Aminocaproic Acid', variants: ['イプシロンアミノカプロン酸', '6-アミノヘキサン酸'] },
  { ja: '酢酸dl-α-トコフェロール', inci: 'Tocopheryl Acetate', variants: ['酢酸トコフェロール（医薬部外品）'] },
  { ja: 'サリチル酸', inci: 'Salicylic Acid', variants: ['o-ヒドロキシ安息香酸', 'β-ヒドロキシ酸', 'BHA'] },
  { ja: 'イソプロピルメチルフェノール', inci: 'Isopropyl Methylphenol', variants: ['IPMP', 'チモール誘導体'] },
  { ja: '塩酸クロルヘキシジン', inci: 'Chlorhexidine Hydrochloride', variants: ['クロルヘキシジン塩酸塩'] },
  { ja: '酸化亜鉛（医薬部外品）', inci: 'Zinc Oxide', variants: ['亜鉛華（医薬部外品）'] },
  { ja: '塩化ナトリウム', inci: 'Sodium Chloride', variants: ['食塩', 'NaCl', '精製塩'] },
  { ja: 'D-パントテニルアルコール', inci: 'Panthenol', variants: ['D-パントテノール', 'パンテノール（医薬部外品）'] },
  { ja: 'ジンクピリチオン', inci: 'Pyrithione Zinc', variants: ['亜鉛ピリチオン', 'ZPT'] },
  { ja: 'セファランチン', inci: 'Cepharanthine', variants: ['セファランチン（育毛成分）'] },
  { ja: 'ミノキシジル', inci: 'Minoxidil', variants: ['ミノキシジル（育毛薬）'] },
  { ja: 'ニコチン酸アミド', inci: 'Niacinamide', variants: ['ニコチン酸アミド（医薬部外品）', 'ビタミンB3アミド'] },
  { ja: 'ニコチン酸トコフェロール', inci: 'Tocopheryl Nicotinate', variants: ['ニコチン酸ビタミンEエステル'] },
  { ja: 'ピリドキシン塩酸塩', inci: 'Pyridoxine HCl', variants: ['ビタミンB6塩酸塩'] },
  { ja: 'リボフラビン', inci: 'Riboflavin', variants: ['ビタミンB2'] },

  // ── 追加：pH調整剤・バッファー ──
  { ja: '水酸化K', inci: 'Potassium Hydroxide', variants: ['水酸化カリウム', 'KOH', '苛性カリ'] },
  { ja: 'リン酸', inci: 'Phosphoric Acid', variants: ['正リン酸', 'H3PO4'] },
  { ja: 'リン酸Na', inci: 'Sodium Phosphate', variants: ['リン酸ナトリウム', 'リン酸一ナトリウム'] },
  { ja: '酢酸', inci: 'Acetic Acid', variants: ['氷酢酸'] },
  { ja: '酢酸Na', inci: 'Sodium Acetate', variants: ['酢酸ナトリウム'] },
  { ja: 'コハク酸', inci: 'Succinic Acid', variants: ['ブタン二酸'] },
  { ja: 'コハク酸Na', inci: 'Disodium Succinate', variants: ['コハク酸ナトリウム'] },
  { ja: 'リンゴ酸', inci: 'Malic Acid', variants: ['L-リンゴ酸', 'DL-リンゴ酸'] },
  { ja: '酒石酸', inci: 'Tartaric Acid', variants: ['L-酒石酸'] },
  { ja: 'グルコン酸', inci: 'Gluconic Acid', variants: ['D-グルコン酸'] },
  { ja: 'グリコール酸', inci: 'Glycolic Acid', variants: ['グリコリック酸', 'AHA', 'ヒドロキシ酢酸'] },
  { ja: 'アミノメチルプロパノール', inci: 'Aminomethyl Propanol', variants: ['AMP', '2-アミノ-2-メチル-1-プロパノール'] },
  { ja: 'ジソジウムEDTA', inci: 'Disodium EDTA', variants: ['EDTA-2Na', 'エチレンジアミン四酢酸二ナトリウム', 'エデト酸二ナトリウム'] },
  { ja: 'テトラソジウムEDTA', inci: 'Tetrasodium EDTA', variants: ['EDTA-4Na', 'エチレンジアミン四酢酸四ナトリウム'] },

  // ── 追加：その他機能性成分 ──
  { ja: 'フィチン酸', inci: 'Phytic Acid', variants: ['イノシトール六リン酸', 'IP6'] },
  { ja: 'フィチン酸Na', inci: 'Sodium Phytate', variants: ['フィチン酸ナトリウム'] },
  { ja: 'ペンテト酸5Na', inci: 'Pentasodium Pentetate', variants: ['DTPA-5Na', 'ジエチレントリアミン五酢酸五ナトリウム'] },
  { ja: 'ブチルヒドロキシトルエン', inci: 'BHT', variants: ['BHT', 'ジブチルヒドロキシトルエン', '酸化防止剤BHT'] },
  { ja: 'ブチルヒドロキシアニソール', inci: 'BHA', variants: ['ブチルヒドロキシアニソール（酸化防止剤）'] },
  { ja: 'ジブチルヒドロキシアニソール', inci: 'BHA', variants: ['DBHA'] },
  { ja: 'プロピルガレート', inci: 'Propyl Gallate', variants: ['没食子酸プロピル'] },
  { ja: 'アスコルビン酸パルミテート', inci: 'Ascorbyl Palmitate', variants: ['パルミチン酸アスコルビル', 'AP'] },
  { ja: 'トコフェロール混合物', inci: 'Mixed Tocopherols', variants: ['天然ビタミンE混合物', 'α+β+γ+δトコフェロール'] },
  { ja: '乾燥水酸化アルミニウム', inci: 'Aluminum Hydroxide', variants: ['水酸化アルミニウム'] },
  { ja: 'ステアリン酸亜鉛', inci: 'Zinc Stearate', variants: ['亜鉛石けん'] },
  { ja: 'ステアリン酸マグネシウム', inci: 'Magnesium Stearate', variants: ['マグネシウムステアレート'] },
  { ja: 'ステアリン酸アルミニウム', inci: 'Aluminum Stearate', variants: ['アルミニウムステアレート'] },
  { ja: 'ジメチコンコポリオール', inci: 'Dimethicone Copolyol', variants: ['PEG-ジメチコン'] },
  { ja: 'アモジメチコン', inci: 'Amodimethicone', variants: ['アミノ変性シリコーン'] },
  { ja: 'シメチコン', inci: 'Simethicone', variants: ['ジメチルポリシロキサンエマルション'] },
  { ja: 'アルキルグリセリル', inci: 'Glyceryl Oleate', variants: ['オレイン酸グリセリル'] },
  { ja: 'ソルビタンオレエート', inci: 'Sorbitan Oleate', variants: ['モノオレイン酸ソルビタン'] },
  { ja: 'グルコサミン', inci: 'Glucosamine', variants: ['D-グルコサミン', 'グルコサミン塩酸塩'] },

  // ── 追加：精油・フレグランス素材 ──
  { ja: 'ベルガモット果実油', inci: 'Citrus Aurantium Bergamia (Bergamot) Fruit Oil', variants: ['ベルガモットオイル'] },
  { ja: 'ジャスミン花エキス', inci: 'Jasminum Officinale (Jasmine) Flower Extract', variants: ['ジャスミンエキス'] },
  { ja: 'ローズ花油', inci: 'Rosa Damascena Flower Oil', variants: ['ローズオイル', 'バラ精油', 'アタルオブローズ'] },
  { ja: 'ユズ果皮油', inci: 'Citrus Junos Peel Oil', variants: ['柚子精油', 'ユズオイル'] },
  { ja: 'ヒノキ葉油', inci: 'Chamaecyparis Obtusa Leaf Oil', variants: ['ヒノキオイル', '檜精油'] },
  { ja: 'ウッドエキス', inci: 'Cedrus Atlantica Bark Oil', variants: ['シダーウッドオイル', 'アトラスシダー油'] },
  { ja: 'イランイラン花油', inci: 'Cananga Odorata Flower Oil', variants: ['イランイランオイル'] },
  { ja: 'フランキンセンス油', inci: 'Boswellia Carterii Oil', variants: ['乳香精油', 'オリバナム油'] },
  { ja: 'サンダルウッド油', inci: 'Santalum Album (Sandalwood) Oil', variants: ['白檀油', 'サンダルウッドオイル'] },
  { ja: 'ゼラニウム花油', inci: 'Pelargonium Graveolens Flower Oil', variants: ['ゼラニウムオイル'] },
];

