// ── 化粧品成分データベース ────────────────────────────────────
// Phase 4.1: 日本語名・INCI名・表記ゆれ辞書（最低100件）
// データソース参考: 日本化粧品工業連合会(JCIA)・厚生労働省・ISO 16128

const INGREDIENTS_DB = [
  // ── 基本溶媒・保湿剤 ──
  { ja: '水', inci: 'Water', variants: ['精製水', 'イオン交換水', 'Aqua', 'Pure Water', '蒸留水', '滅菌精製水'] },
  { ja: 'グリセリン', inci: 'Glycerin', variants: ['グリセロール', 'Glycerol', '濃グリセリン', '精製グリセリン'] },
  { ja: 'ブチレングリコール', inci: 'Butylene Glycol', variants: ['1,3-ブチレングリコール', '1,3-BG', 'BG', '1,3-ブタンジオール'] },
  { ja: 'プロパンジオール', inci: 'Propanediol', variants: ['1,3-プロパンジオール', 'プロピレングリコール代替'] },
  { ja: 'プロピレングリコール', inci: 'Propylene Glycol', variants: ['1,2-プロパンジオール', 'PG'] },
  { ja: 'ペンチレングリコール', inci: 'Pentylene Glycol', variants: ['1,2-ペンタンジオール'] },
  { ja: 'ヘキシレングリコール', inci: 'Hexylene Glycol', variants: [] },
  { ja: 'ジプロピレングリコール', inci: 'Dipropylene Glycol', variants: ['DPG'] },
  { ja: 'エタノール', inci: 'Alcohol', variants: ['アルコール', 'エチルアルコール', '95%エタノール', '変性アルコール', 'Ethyl Alcohol', 'Denatured Alcohol'] },
  { ja: 'イソプロパノール', inci: 'Isopropanol', variants: ['イソプロピルアルコール', '2-プロパノール'] },

  // ── 油性成分・エモリエント ──
  { ja: 'スクワラン', inci: 'Squalane', variants: ['植物性スクワラン', 'スクアラン'] },
  { ja: 'ホホバ種子油', inci: 'Simmondsia Chinensis (Jojoba) Seed Oil', variants: ['ホホバオイル', 'ジョジョバ油'] },
  { ja: 'シア脂', inci: 'Butyrospermum Parkii (Shea) Butter', variants: ['シアバター', 'カリテバター', 'Shea Butter'] },
  { ja: 'アルガニアスピノサ核油', inci: 'Argania Spinosa Kernel Oil', variants: ['アルガンオイル', 'アルガン油'] },
  { ja: 'ローズヒップ果実油', inci: 'Rosa Canina Fruit Oil', variants: ['ローズヒップオイル'] },
  { ja: 'オリーブ果実油', inci: 'Olea Europaea (Olive) Fruit Oil', variants: ['オリーブオイル', 'オリーブ油'] },
  { ja: 'ヒマワリ種子油', inci: 'Helianthus Annuus (Sunflower) Seed Oil', variants: ['ひまわり油', 'サンフラワーオイル'] },
  { ja: 'パーム油', inci: 'Elaeis Guineensis (Palm) Oil', variants: ['パームオイル'] },
  { ja: 'ヤシ油', inci: 'Cocos Nucifera (Coconut) Oil', variants: ['ココナッツオイル', 'コプラ油'] },
  { ja: 'ミネラルオイル', inci: 'Mineral Oil', variants: ['流動パラフィン', '白色ワセリン', 'Paraffinum Liquidum'] },
  { ja: 'ワセリン', inci: 'Petrolatum', variants: ['白色ワセリン', 'Petroleum Jelly'] },
  { ja: 'パラフィン', inci: 'Paraffin', variants: ['固形パラフィン', 'ハードパラフィン'] },
  { ja: 'セレシン', inci: 'Ceresin', variants: ['セレシンワックス', 'Ceresine'] },
  { ja: 'マイクロクリスタリンワックス', inci: 'Microcrystalline Wax', variants: ['マイクロワックス'] },
  { ja: 'カルナウバロウ', inci: 'Copernicia Cerifera (Carnauba) Wax', variants: ['カルナウバワックス', 'Brazil Wax'] },
  { ja: 'ミツロウ', inci: 'Cera Alba', variants: ['蜜蝋', 'ビーズワックス', 'Beeswax', '白色蜜蝋'] },
  { ja: 'ラノリン', inci: 'Lanolin', variants: ['羊毛脂', '精製ラノリン', 'Wool Fat'] },
  { ja: 'イソノナン酸イソノニル', inci: 'Isononyl Isononanoate', variants: [] },
  { ja: 'カプリル酸カプリン酸トリグリセリド', inci: 'Caprylic/Capric Triglyceride', variants: ['MCTオイル', 'フラクション化ヤシ油', 'GTCC'] },
  { ja: 'エチルヘキサン酸セチル', inci: 'Cetyl Ethylhexanoate', variants: ['オクタン酸セチル'] },
  { ja: 'ジメチコン', inci: 'Dimethicone', variants: ['ポリジメチルシロキサン', 'シリコーン', 'PDMS', 'ジメチルポリシロキサン'] },
  { ja: 'シクロメチコン', inci: 'Cyclomethicone', variants: ['シクロペンタシロキサン'] },
  { ja: 'シクロペンタシロキサン', inci: 'Cyclopentasiloxane', variants: ['D5', 'シクロD5'] },
  { ja: 'フェニルトリメチコン', inci: 'Phenyl Trimethicone', variants: [] },

  // ── 乳化剤・界面活性剤 ──
  { ja: 'ステアリン酸', inci: 'Stearic Acid', variants: [] },
  { ja: 'パルミチン酸', inci: 'Palmitic Acid', variants: [] },
  { ja: 'セテアリルアルコール', inci: 'Cetearyl Alcohol', variants: ['セチルアルコール・ステアリルアルコール混合物'] },
  { ja: 'セチルアルコール', inci: 'Cetyl Alcohol', variants: ['セタノール', 'パルミチルアルコール'] },
  { ja: 'ステアリルアルコール', inci: 'Stearyl Alcohol', variants: [] },
  { ja: 'セテアレス-20', inci: 'Ceteareth-20', variants: [] },
  { ja: 'PEG-40水添ヒマシ油', inci: 'PEG-40 Hydrogenated Castor Oil', variants: ['HCO-40'] },
  { ja: 'ポリソルベート80', inci: 'Polysorbate 80', variants: ['Tween80', 'ポリオキシエチレン(20)ソルビタンモノオレエート'] },
  { ja: 'ポリソルベート20', inci: 'Polysorbate 20', variants: ['Tween20'] },
  { ja: 'レシチン', inci: 'Lecithin', variants: ['大豆レシチン', '卵黄レシチン', 'ホスファチジルコリン'] },
  { ja: 'グリセリル脂肪酸エステル', inci: 'Glyceryl Stearate', variants: ['ステアリン酸グリセリル', 'グリセリルモノステアレート'] },
  { ja: 'ベヘニルアルコール', inci: 'Behenyl Alcohol', variants: ['ドコサノール', '1-ドコサノール'] },
  { ja: 'ラウレス硫酸ナトリウム', inci: 'Sodium Laureth Sulfate', variants: ['SLES', 'ポリオキシエチレンラウリル硫酸ナトリウム'] },
  { ja: 'ラウリル硫酸ナトリウム', inci: 'Sodium Lauryl Sulfate', variants: ['SLS', 'ドデシル硫酸ナトリウム'] },
  { ja: 'コカミドプロピルベタイン', inci: 'Cocamidopropyl Betaine', variants: ['ヤシ油脂肪酸アミドプロピルベタイン', 'CAPB'] },
  { ja: 'コカミドMEA', inci: 'Cocamide MEA', variants: ['ヤシ油脂肪酸モノエタノールアミド'] },

  // ── 増粘剤・安定剤 ──
  { ja: 'カルボマー', inci: 'Carbomer', variants: ['カルボキシビニルポリマー', 'アクリル酸ポリマー', 'CVP'] },
  { ja: 'キサンタンガム', inci: 'Xanthan Gum', variants: ['キサンタン', 'キサンタンゴム'] },
  { ja: 'ヒドロキシエチルセルロース', inci: 'Hydroxyethylcellulose', variants: ['HEC'] },
  { ja: 'ヒドロキシプロピルセルロース', inci: 'Hydroxypropyl Cellulose', variants: ['HPC'] },
  { ja: 'カルボキシメチルセルロースナトリウム', inci: 'Cellulose Gum', variants: ['CMC', 'CMC-Na'] },
  { ja: '寒天', inci: 'Agar', variants: ['アガー'] },
  { ja: 'カラギーナン', inci: 'Carrageenan', variants: ['カラゲナン'] },
  { ja: 'ヒドロキシプロピルグアーガム', inci: 'Hydroxypropyl Guar', variants: [] },
  { ja: 'アクリレーツコポリマー', inci: 'Acrylates Copolymer', variants: [] },

  // ── 保湿成分・機能性成分 ──
  { ja: 'ヒアルロン酸Na', inci: 'Sodium Hyaluronate', variants: ['ヒアルロン酸ナトリウム', 'ヒアルロン酸', 'Hyaluronic Acid', 'HA'] },
  { ja: 'コラーゲン', inci: 'Soluble Collagen', variants: ['可溶性コラーゲン', '水溶性コラーゲン', 'コラーゲンペプチド'] },
  { ja: 'エラスチン', inci: 'Hydrolyzed Elastin', variants: ['加水分解エラスチン'] },
  { ja: 'セラミドNP', inci: 'Ceramide NP', variants: ['セラミド2', 'Ceramide 2', 'セラミドII'] },
  { ja: 'セラミドAP', inci: 'Ceramide AP', variants: ['セラミド6II', 'Ceramide 6II'] },
  { ja: 'セラミドEOP', inci: 'Ceramide EOP', variants: ['セラミド1', 'Ceramide 1'] },
  { ja: 'スフィンゴ糖脂質', inci: 'Glycosphingolipids', variants: ['糖セラミド'] },
  { ja: 'ナイアシンアミド', inci: 'Niacinamide', variants: ['ニコチン酸アミド', 'ビタミンB3', 'Nicotinamide'] },
  { ja: 'アスコルビン酸', inci: 'Ascorbic Acid', variants: ['ビタミンC', 'L-アスコルビン酸'] },
  { ja: 'アスコルビン酸グルコシド', inci: 'Ascorbyl Glucoside', variants: ['アスコルビルグルコシド', 'AA-2G'] },
  { ja: 'リン酸L-アスコルビルMg', inci: 'Magnesium Ascorbyl Phosphate', variants: ['リン酸アスコルビルマグネシウム', 'MAP'] },
  { ja: 'レチノール', inci: 'Retinol', variants: ['ビタミンA', 'Vitamin A'] },
  { ja: 'パルミチン酸レチニル', inci: 'Retinyl Palmitate', variants: ['レチノールパルミテート'] },
  { ja: 'トコフェロール', inci: 'Tocopherol', variants: ['ビタミンE', 'α-トコフェロール', 'dl-α-トコフェロール'] },
  { ja: '酢酸トコフェロール', inci: 'Tocopheryl Acetate', variants: ['ビタミンE酢酸エステル', 'dl-α-トコフェリルアセテート'] },
  { ja: 'パンテノール', inci: 'Panthenol', variants: ['D-パンテノール', 'プロビタミンB5', 'パントテノール'] },
  { ja: 'アラントイン', inci: 'Allantoin', variants: ['アラントイン（グリコール酸） ジウレア'] },
  { ja: 'ビサボロール', inci: 'Bisabolol', variants: ['α-ビサボロール', 'Bisabolol'] },
  { ja: 'グルコン酸亜鉛', inci: 'Zinc Gluconate', variants: [] },
  { ja: 'レゾルシノール', inci: 'Resorcinol', variants: ['m-ジヒドロキシベンゼン'] },
  { ja: 'カフェイン', inci: 'Caffeine', variants: ['無水カフェイン'] },

  // ── 防腐剤・抗菌剤 ──
  { ja: 'フェノキシエタノール', inci: 'Phenoxyethanol', variants: ['エチレングリコールモノフェニルエーテル'] },
  { ja: 'メチルパラベン', inci: 'Methylparaben', variants: ['パラオキシ安息香酸メチル', '4-ヒドロキシ安息香酸メチル'] },
  { ja: 'エチルパラベン', inci: 'Ethylparaben', variants: ['パラオキシ安息香酸エチル'] },
  { ja: 'プロピルパラベン', inci: 'Propylparaben', variants: ['パラオキシ安息香酸プロピル'] },
  { ja: 'ブチルパラベン', inci: 'Butylparaben', variants: ['パラオキシ安息香酸ブチル'] },
  { ja: '安息香酸Na', inci: 'Sodium Benzoate', variants: ['安息香酸ナトリウム'] },
  { ja: 'ソルビン酸K', inci: 'Potassium Sorbate', variants: ['ソルビン酸カリウム'] },
  { ja: 'クロルヘキシジン', inci: 'Chlorhexidine', variants: ['塩酸クロルヘキシジン', 'グルコン酸クロルヘキシジン'] },
  { ja: '塩化ベンザルコニウム', inci: 'Benzalkonium Chloride', variants: ['BAC', '逆性石けん'] },
  { ja: 'エチルヘキシルグリセリン', inci: 'Ethylhexylglycerin', variants: ['オクタン酸グリセリン誘導体'] },
  { ja: 'カプリリルグリコール', inci: 'Caprylyl Glycol', variants: ['オクタン-1,2-ジオール'] },

  // ── pH調整剤 ──
  { ja: 'クエン酸', inci: 'Citric Acid', variants: ['無水クエン酸'] },
  { ja: 'クエン酸Na', inci: 'Sodium Citrate', variants: ['クエン酸ナトリウム'] },
  { ja: '乳酸', inci: 'Lactic Acid', variants: ['L-乳酸', 'DL-乳酸'] },
  { ja: '乳酸Na', inci: 'Sodium Lactate', variants: ['乳酸ナトリウム'] },
  { ja: '水酸化Na', inci: 'Sodium Hydroxide', variants: ['水酸化ナトリウム', '苛性ソーダ', 'NaOH'] },
  { ja: 'トリエタノールアミン', inci: 'Triethanolamine', variants: ['TEA', 'トリオールアミン'] },
  { ja: 'アルギニン', inci: 'Arginine', variants: ['L-アルギニン', '塩基性アミノ酸'] },

  // ── 紫外線吸収剤・散乱剤 ──
  { ja: 'エチルヘキシルメトキシシンナメート', inci: 'Ethylhexyl Methoxycinnamate', variants: ['オクチルメトキシシンナメート', 'OMC'] },
  { ja: 'ベンゾフェノン-4', inci: 'Benzophenone-4', variants: ['スルホイソベンゾフェノン', 'BP-4'] },
  { ja: 'ビスエチルヘキシルオキシフェノールメトキシフェニルトリアジン', inci: 'Bis-Ethylhexyloxyphenol Methoxyphenyl Triazine', variants: ['Tinosorb S'] },
  { ja: '酸化チタン', inci: 'Titanium Dioxide', variants: ['二酸化チタン', 'CI 77891', '微粒子酸化チタン'] },
  { ja: '酸化亜鉛', inci: 'Zinc Oxide', variants: ['亜鉛華', 'CI 77947', '微粒子酸化亜鉛'] },
  { ja: 'オクトクリレン', inci: 'Octocrylene', variants: [] },

  // ── 着色料 ──
  { ja: '酸化鉄', inci: 'Iron Oxides', variants: ['ベンガラ', 'CI 77491', 'CI 77492', 'CI 77499', '酸化鉄（赤）', '酸化鉄（黄）', '酸化鉄（黒）'] },
  { ja: 'タルク', inci: 'Talc', variants: ['タルク（複合粉体）', 'CI 77718'] },
  { ja: 'マイカ', inci: 'Mica', variants: ['雲母', 'CI 77019'] },
  { ja: 'カオリン', inci: 'Kaolin', variants: ['白色カオリン', 'チャイナクレー'] },
  { ja: '黄酸化鉄', inci: 'CI 77492', variants: ['Iron Oxide Yellow'] },
  { ja: '赤色226号', inci: 'CI 12085', variants: ['D&C Red No.6'] },
  { ja: '青色1号', inci: 'CI 42090', variants: ['FD&C Blue No.1', 'ブリリアントブルーFCF'] },

  // ── 植物エキス ──
  { ja: 'アロエベラ葉エキス', inci: 'Aloe Barbadensis Leaf Extract', variants: ['アロエエキス', 'アロエ液汁'] },
  { ja: 'カミツレ花エキス', inci: 'Chamomilla Recutita (Matricaria) Flower Extract', variants: ['カモミールエキス', 'カミルレエキス'] },
  { ja: 'センテラアジアチカエキス', inci: 'Centella Asiatica Extract', variants: ['ツボクサエキス', 'CICA', 'シカエキス'] },
  { ja: 'ユーカリ葉エキス', inci: 'Eucalyptus Globulus Leaf Extract', variants: ['ユーカリエキス'] },
  { ja: 'ラベンダー花エキス', inci: 'Lavandula Angustifolia (Lavender) Flower Extract', variants: ['ラベンダーエキス'] },
  { ja: '緑茶エキス', inci: 'Camellia Sinensis Leaf Extract', variants: ['チャ葉エキス', 'グリーンティーエキス'] },
  { ja: 'バーチ樹皮エキス', inci: 'Betula Alba Bark Extract', variants: ['白樺エキス', 'ビルベリーエキス'] },
  { ja: 'リコリスエキス', inci: 'Glycyrrhiza Glabra (Licorice) Root Extract', variants: ['カンゾウエキス', 'グリチルリチン酸関連'] },
  { ja: 'グリチルリチン酸2K', inci: 'Dipotassium Glycyrrhizate', variants: ['グリチルリチン酸ジカリウム'] },
  { ja: 'フラーレン', inci: 'Fullerene', variants: ['C60', 'バックミンスターフラーレン'] },

  // ── 香料・精油 ──
  { ja: '香料', inci: 'Fragrance', variants: ['Parfum', 'フレグランス', '調合香料', '天然香料', '合成香料'] },
  { ja: 'ラベンダー油', inci: 'Lavandula Angustifolia (Lavender) Oil', variants: ['ラベンダーオイル', 'ラベンダー精油'] },
  { ja: 'ローズマリー葉油', inci: 'Rosmarinus Officinalis (Rosemary) Leaf Oil', variants: ['ローズマリーオイル'] },
  { ja: 'ティーツリー葉油', inci: 'Melaleuca Alternifolia (Tea Tree) Leaf Oil', variants: ['ティーツリーオイル'] },
  { ja: 'ペパーミント油', inci: 'Mentha Piperita (Peppermint) Oil', variants: ['ハッカ油', 'ペパーミントオイル'] },
];
